# -*- coding: utf-8 -*-
"""Streamlit dashboard for Pricing Truth Machine visualizations."""

from pathlib import Path

import streamlit as st

from ptm_viz.charts import create_price_comparison_chart
from ptm_viz.components import (
    render_citations_list,
    render_evidence_table,
    render_gaps_panel,
    render_verdict_panel,
)
from ptm_viz.loader import load_report_json, validate_report_structure
from ptm_viz.transforms import (
    build_competitor_table,
    build_price_comparison_data,
    get_product_info,
)

# Page config
st.set_page_config(
    page_title="Pricing Truth Machine - Dashboard",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Title
st.title("📊 Pricing Truth Machine Dashboard")
st.markdown("Evidence-based pricing analysis visualization")

# Sidebar - File selection
st.sidebar.header("📁 Load Report")
st.sidebar.markdown("Upload a `report.json` file or select from local directory.")

uploaded_file = st.sidebar.file_uploader(
    "Upload report.json",
    type=["json"],
    help="Upload a report.json file generated by PTM",
)

# Also allow selecting from output directory
output_dir = Path("output")
report_path = None

if uploaded_file is not None:
    # Save uploaded file temporarily
    import tempfile
    with tempfile.NamedTemporaryFile(delete=False, suffix=".json", mode="w") as tmp:
        import json
        data = json.load(uploaded_file)
        json.dump(data, tmp)
        report_path = Path(tmp.name)
else:
    # Check if output/report.json exists
    default_report = output_dir / "report.json"
    if default_report.exists():
        if st.sidebar.button("📂 Load Default Report", use_container_width=True):
            report_path = default_report
            st.sidebar.success(f"Loaded: {default_report}")
    else:
        st.sidebar.info("No default report found. Upload a report.json file.")

# Manual path input
manual_path = st.sidebar.text_input(
    "Or enter file path:",
    value="output/report.json",
    help="Enter path to report.json file",
)

if manual_path and Path(manual_path).exists():
    if st.sidebar.button("📂 Load from Path", use_container_width=True):
        report_path = Path(manual_path)

# Load and validate report
if report_path and report_path.exists():
    data = load_report_json(report_path)
    
    if data:
        is_valid, warnings = validate_report_structure(data)
        
        if warnings:
            for warning in warnings:
                st.sidebar.warning(warning)
        
        if is_valid or data:  # Proceed even with warnings
            # Get product info
            product_info = get_product_info(data)
            
            # Header with product identity
            st.header(f"Product: {product_info['name']}")
            st.markdown(f"**URL:** [{product_info['url']}]({product_info['url']})")
            st.markdown(f"**Current Price:** {product_info['current_price']}")
            
            st.divider()
            
            # Verdict panel
            st.subheader("Verdict")
            render_verdict_panel(data)
            
            st.divider()
            
            # Price comparison chart
            st.subheader("Price Comparison")
            comparison_df, current_price = build_price_comparison_data(data)
            
            if not comparison_df.empty:
                chart = create_price_comparison_chart(
                    comparison_df,
                    product_name=product_info["name"],
                )
                st.plotly_chart(chart, use_container_width=True)
                
                # Show summary stats
                competitor_prices = comparison_df[comparison_df["Is Product"] == False]["Price (USD/month)"]
                if not competitor_prices.empty and current_price is not None:
                    col1, col2, col3, col4 = st.columns(4)
                    with col1:
                        st.metric("Your Price", f"${current_price:.2f}")
                    with col2:
                        avg_price = competitor_prices.mean()
                        st.metric("Avg Competitor", f"${avg_price:.2f}")
                    with col3:
                        min_price = competitor_prices.min()
                        st.metric("Min Competitor", f"${min_price:.2f}")
                    with col4:
                        max_price = competitor_prices.max()
                        st.metric("Max Competitor", f"${max_price:.2f}")
            else:
                st.info("No comparable competitor prices available for chart.")
                st.markdown("This may be due to missing cadence information or normalization issues.")
            
            st.divider()
            
            # Evidence table
            competitor_df = build_competitor_table(data)
            render_evidence_table(competitor_df)
            
            st.divider()
            
            # Gaps panel
            st.subheader("Gaps & Limitations")
            render_gaps_panel(data)
            
            st.divider()
            
            # Citations
            st.subheader("Citations")
            render_citations_list(data)
            
            st.divider()
            
            # Optional: Dataflow diagram (Mermaid)
            with st.expander("🔧 Dataflow Diagram (Technical)"):
                st.markdown("""
                ```mermaid
                flowchart LR
                    A[User Inputs] --> B[Validator]
                    B --> C[Tavily Search]
                    C --> D[Evidence Extractor]
                    D --> E[Price Parser]
                    E --> F[Verdict Engine]
                    F --> G[Report JSON/MD]
                ```
                """)
            
            # Optional: Run metadata
            with st.expander("📋 Run Metadata"):
                metadata = data.get("metadata", {})
                verdict = data.get("verdict", {})
                evidence_bundle = verdict.get("evidence_bundle", {})
                
                st.json({
                    "schema_version": metadata.get("schema_version", "unknown"),
                    "sources_retrieved": len(evidence_bundle.get("tavily_sources", [])),
                    "competitors_analyzed": len(evidence_bundle.get("competitor_pricing", [])),
                    "comparable_competitors": verdict.get("competitor_count", 0),
                })
        else:
            st.error("Report structure is invalid. Please check the file format.")
    else:
        st.error("Failed to load report. Please check the file.")
else:
    # Welcome screen
    st.info("👈 Please load a report.json file using the sidebar.")
    st.markdown("""
    ### How to use:
    1. Run PTM analysis to generate a `report.json` file
    2. Upload the file using the sidebar, or
    3. Place it in the `output/` directory and click "Load Default Report"
    
    ### What you'll see:
    - **Verdict Panel**: Status and confidence of the pricing analysis
    - **Price Comparison Chart**: Visual comparison of your product vs competitors
    - **Evidence Table**: Detailed evidence with source URLs and verbatim quotes
    - **Gaps & Limitations**: Data gaps that affect confidence
    - **Citations**: All sources used in the analysis
    """)
